"""Minimal type stubs for psycopg_pool used by the project.

These intentionally keep types permissive to avoid downstream invariant/generic
errors until a proper upstream stub is available.
"""
from typing import Any, AsyncIterator, Iterator, Optional

class AsyncConnection: ...

class AsyncConnectionPool:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def acquire(self) -> AsyncConnection: ...
    async def release(self, conn: AsyncConnection) -> None: ...
    async def close(self) -> None: ...
    async def __aenter__(self) -> AsyncConnection: ...
    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...

__all__ = ["AsyncConnection", "AsyncConnectionPool"]
# Local type stub for psycopg_pool to relax generics for pyright
from typing import Any, AsyncIterator, Optional, Dict, Type

class AsyncConnection: ...

class AsyncConnectionPool:
    def __init__(self, conninfo: str = ..., *, connection_class: Type[Any] = ..., kwargs: Optional[Dict[str, Any]] = ..., min_size: int = ..., max_size: Optional[int] = ..., open: Optional[bool] = ..., **kwargs2: Any) -> None: ...
    async def open(self, wait: bool = False, timeout: float = 30.0) -> None: ...
    async def close(self, timeout: float = 5.0) -> None: ...
    async def connection(self, timeout: Optional[float] = None) -> AsyncIterator[Any]: ...
    async def getconn(self, timeout: Optional[float] = None) -> Any: ...
    async def putconn(self, conn: Any) -> None: ...
    async def wait(self, timeout: float = 30.0) -> None: ...
    async def resize(self, min_size: int, max_size: Optional[int] = None) -> None: ...
    async def __aenter__(self) -> 'AsyncConnectionPool': ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...
