name: CI - Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, order-service, web-gateway]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv pytest coverage pytest-cov httpx pytest-asyncio

      - name: Validate environment (CI)
        run: |
          python3 scripts/validate_env.py --ci
      - name: Run service tests (with coverage)
        run: |
          make test SERVICE=${{ matrix.service }}
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.service }}
          path: |
            services/${{ matrix.service }}/coverage.xml
